### ISSUE TITLE
distutils got removed in python 3.12

### ISSUE THREAD

**Issue by chenrui333** [chaos/genders#65]
Python 3.12 has removed `distutils`: https://docs.python.org/3.12/whatsnew/3.12.html#removed

relates to https://github.com/Homebrew/homebrew-core/pull/181477

**Comment by chu11** [comment]
thanks for the note.  Unfortunately just moving from distutils to setuptools has not been smooth sailing this morning.  `setuptools` appears to require PYTHONPATH to be setup before it can install.  This mucks w/ the integration w/ automake.

This travesty of a change finally allowed me to build an RPM, but it obviously does not honor the `prefix` path that may be requested by a user.

```
 install:
-       $(PYTHON) genderssetup.py install --prefix=$(PYTHON_DESTDIR)$(prefix) --exec-prefix=$(PYTHON_DESTDIR)$(exec_prefix)
+       echo -n $(PYTHON_DESTDIR) > python.site
+       $(PYTHON) -c "import site; print(site.getsitepackages()[0])" >> python.site
+       mkdir -p $$(cat python.site)
+       PYTHONPATH=$$(cat python.site) $(PYTHON) genderssetup.py install --prefix=$(PYTHON_DESTDIR)$(prefix) --exec-prefix=$(PYTHON_DESTDIR)$(exec_prefix)
```

Not sure if there's an alternate trick you know of?

**Comment by chu11** [comment]
ahhh

https://github.com/spack/spack/issues/1036

gave me a great hint

`--single-version-externally-managed --root=/`

seems to do the trick.
