### ISSUE TITLE
[v1.22] build errors on Mac OS X: 'bad HTML entity'

### ISSUE THREAD

**Issue by dunn** [chaos/genders#9]
While generating the javadoc, `make` fails with the following two errors:

```
./gov/llnl/lc/chaos/Genders.java:170: error: bad HTML entity
     * with '||', intersection with '&&', * difference with '--', and
                                     ^
./gov/llnl/lc/chaos/Genders.java:170: error: bad HTML entity
     * with '||', intersection with '&&', * difference with '--', and
                                      ^
```

Full logs: https://gist.github.com/dunn/844d0e975e137b995dec#file-02-make-L491-L496

**Comment by chu11** [comment]
I assume probably need to do HTML special chars.  Or as stackoverflow states, remove doclint.

http://stackoverflow.com/questions/24403298/netbean-error-missing-semicolonjava-comment

**Comment by Alessandro-Barbieri** [comment]
see https://bugzilla.redhat.com/show_bug.cgi?id=1217007
see https://src.fedoraproject.org/rpms/genders/blob/master/f/genders-1.22-javadoc.patch

**Comment by Alessandro-Barbieri** [comment]
Is it possible to merge the patch?

**Comment by BenCasses** [comment]
patched
